### ISSUE TITLE
Can't Find Mendeley Desktop: Dependencies Mendeley Desktop - Failed

### ISSUE THREAD

**Issue by jsbangsund** [grahamrow/zim-mendeley-plugin#5]
Hi, 
I'm running Windows, and I've cloned the plugin to my plugins folder (%appdata%\zim\data\zim\plugins), and zim (version 0.65) can find the plugin, but it can't find Mendeley Desktop (which is stored at C:\Program Files (x86)\Mendeley Desktop). How can I get the plugin to recognize that I have Mendeley desktop installed? Is there a path or environment variable I need to change?

Thanks,
John

**Comment by FlorianWanders** [comment]
Same here (zim version 0.63, WIndows), receiving the following error message in zim: Mendeley Desktop - Failed.

**Comment by grahamrow** [comment]
It's probably a path thing, but I disabled the check for the time being. This was also an issue on mac — perhaps Mendeley doesn't install a command line tool anymore? Sorry for the slow response, please let me know if this fixes your issue.

**Comment by FlorianWanders** [comment]
Thanks so much, issue resolved for me!
